Travis build troubleshooting [not ready yet]
IBM/ibm-helm-api-operator pull request #34
Opened 2020-04-28 14:25 UTC by bluzarraga

2020-04-28 20:36 UTC, bluzarraga commented
@bitscuit @cheewaio this pr is ready for review, no rush though

2020-04-29 00:18 UTC, cheewaio requested changes

2020-04-29 00:18 UTC, cheewaio commented on Makefile
> +CSV_VERSION ?= 3.5.0 #TODO change this to 3.6.0 before merging
we should keep it 3.6.0

2020-04-29 00:18 UTC, cheewaio commented on deploy/olm-catalog/ibm-helm-api-operator/3.5.0/operator.ibm.com_helmapis_crd.yaml
>  kind: CustomResourceDefinition
We have to go back to change 3.5.0 CRD?

2020-04-29 00:18 UTC, cheewaio commented on deploy/olm-catalog/ibm-helm-api-operator/0.0.1/operator.ibm.com_helmapis_crd.yaml
>  kind: CustomResourceDefinition
We have to go back to change 0.0.1 CRD?

2020-04-29 00:18 UTC, cheewaio commented on deploy/crds/operator.ibm.com_helmapis_crd.yaml
> +                resources:
the merge here does look right? Did u try installing the CRD?

2020-04-29 00:18 UTC, cheewaio commented on helm-charts/helm-api/values.yaml
> +nodeSelector:
we should remove nodeSelector all together ..there have been 2 build break because of this

2020-04-29 18:21 UTC, cheewaio commented
/lgtm

2020-04-29 18:22 UTC, merged