Cleanup2
IBM/ibm-helm-api-operator pull request #45
Opened 2020-05-12 20:30 UTC by bluzarraga

2020-05-12 20:41 UTC, bitscuit requested changes

2020-05-12 20:41 UTC, bitscuit commented on helm-charts/helm-api/ibm_cloud_pak/manifest.yaml
> +    pull-repository: quay.io/opencloudio/icp-helm-api@sha256:8551180b18e4273775e258ebf3680ab7096ddd68d5d6e01b65e5c3c9661fffb4
icp-helm-api is at 3.4.1 and digest is `e73ac971497212eb3b8904918aa975136c8e8e8c47a520273e51e65fd9bff214` now

2020-05-12 20:41 UTC, bitscuit commented on helm-charts/helm-api/ibm_cloud_pak/manifest.yaml
> +    pull-repository: quay.io/opencloudio/icp-helm-rudder@sha256:5eba2b4052eb80a7ed1e0a91f3e0bcd1e4ae8412e604cfd4dc990daf2e9da9c7
icp-helm-rudder is at 3.3.1 and digest is `437c980277a700f7f53db1ac88ae1d10488033b52422bf17654a82717c6f22af` now

2020-05-12 20:41 UTC, bitscuit commented on helm-charts/helm-api/ibm_cloud_pak/manifest.yaml
> +    pull-repository: quay.io/opencloudio/tiller@sha256:bce0b2a08c309e41f08b5026d1a3904c271b09a2071d0380b90b47aae050cd7f
tiller is at v2.16.1-cs-3.3.1 and digest is `a7539700cdc49623efd9c049760d9b5c32329c498be55f30a87835afdc43fe47`

2020-05-13 14:40 UTC, bitscuit commented
Couple more files that are using old digest values

https://github.com/IBM/ibm-helm-api-operator/blob/cleanup2/deploy/operator.yaml#L60-L65
https://github.com/IBM/ibm-helm-api-operator/blob/cleanup2/deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml#L260-L265

2020-05-13 14:42 UTC, cheewaio requested changes
to update operand image digest, there are a few places you will need to update
- operator.yaml
- csv
- values.yaml
- manifest.yaml

2020-05-13 14:42 UTC, cheewaio commented on helm-charts/helm-api/ibm_cloud_pak/manifest.yaml
> +    pull-repository: quay.io/opencloudio/tiller@sha256:a7539700cdc49623efd9c049760d9b5c32329c498be55f30a87835afdc43fe47
should the digest be arch specific?

2020-05-13 14:43 UTC, bluzarraga commented on helm-charts/helm-api/ibm_cloud_pak/manifest.yaml
> +    pull-repository: quay.io/opencloudio/tiller@sha256:a7539700cdc49623efd9c049760d9b5c32329c498be55f30a87835afdc43fe47
The bundle likes it that way

2020-05-13 15:03 UTC, cheewaio approved these changes
/lgtm

2020-05-13 15:04 UTC, merged